import bcrypt from 'bcryptjs'; import { connectDB, db } from './db/index.js'; import { now } from './clock.js';
if(process.env.SEED_ALLOW_DESTRUCTIVE!=='true')throw new Error('Seed deletes demo collections. Set SEED_ALLOW_DESTRUCTIVE=true only for an intentional demo reset.');if(process.env.NODE_ENV==='production')throw new Error('Demo seeding is disabled in production.');if(!process.env.SEED_DEMO_PASSWORD||process.env.SEED_DEMO_PASSWORD.length<12)throw new Error('Set SEED_DEMO_PASSWORD to a private password of at least 12 characters.');
await connectDB(); const collections=['tasks','offers','donations','drivers','shelter_settings','users','organizations','events'];for(const n of collections)await db.collection(n).deleteMany({});
const password=await bcrypt.hash(process.env.SEED_DEMO_PASSWORD,12),at=now().toISOString();const donors=[],shelters=[];
for(const [i,name] of ['Masala Junction','Campus Mess','Marigold Banquets','Crumb & Co Bakery','Green Leaf Caterers','Royal Tiffin'].entries()){const id=crypto.randomUUID();donors.push(id);await db.collection('organizations').insertOne({id,type:'donor',name,lat:17.38+i*.012,lng:78.48+i*.009,address:`Demo address ${i+1}`,verified:true,created_at:at});}
for(const [i,name] of ['Hope Kitchen','Sunrise Shelter','Seva Home','Little Steps','Care Collective','Nayi Disha'].entries()){const id=crypto.randomUUID();shelters.push(id);await db.collection('organizations').insertOne({id,type:'shelter',name,lat:17.40+i*.01,lng:78.50+i*.008,address:`Demo shelter ${i+1}`,verified:true,remaining_capacity:80+i*20,accepts_veg:true,accepts_nonveg:i%2===1,need_score:.55+i*.06,reliability_score:.7+i*.05,received_today:0,created_at:at});}
for(let i=0;i<donors.length;i++)await db.collection('users').insertOne({id:crypto.randomUUID(),role:'donor',email:`donor${i+1}@demo.local`,password_hash:password,org_id:donors[i],name:`Donor ${i+1}`,created_at:at});for(let i=0;i<shelters.length;i++)await db.collection('users').insertOne({id:crypto.randomUUID(),role:'shelter',email:`shelter${i+1}@demo.local`,password_hash:password,org_id:shelters[i],name:`Shelter ${i+1}`,created_at:at});await db.collection('users').insertOne({id:crypto.randomUUID(),role:'admin',email:'admin@demo.local',password_hash:password,name:'Demo Admin',created_at:at});
for(let i=0;i<5;i++){const uid=crypto.randomUUID();await db.collection('users').insertOne({id:uid,role:'driver',email:`driver${i+1}@demo.local`,password_hash:password,name:`Driver ${i+1}`,created_at:at});await db.collection('drivers').insertOne({id:uid,user_id:uid,lat:17.39+i*.01,lng:78.49+i*.01,is_available:true,vehicle_type:i%2?'bike':'van',claim_rate:.65,completed_count:10,last_seen:at});}
console.log('Seeded demo organizations and accounts (donor1@demo.local, shelter1@demo.local, admin@demo.local). Password is the configured SEED_DEMO_PASSWORD.');await (await import('./db/index.js')).closeDB();
